# Generated by Django 2.0 on 2017-12-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterdebt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='briefContent',
            field=models.CharField(default='Some content', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='static/img/dj.jpg', max_length=255),
        ),
    ]
